language: python
dist: xenial
python: '3.7'
sudo: false
jobs:
  include:
  - stage: test
    install: pip3 install twilio flask fuzzywuzzy requests firebase_admin
    script: echo "Temporary holding place until the test suite exists"
  - stage: deploy
    install: skip
    script: curl $DEPLOY_SCRIPT | bash
    after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - "./send.sh success $WEBHOOK_URL"
stages:
- test
- name: deploy
  if: type = push AND repo = orange-alliance/TOA-Text AND branch = master
env:
  global:
    secure: VPWUeKdzlckinzP3LU73DELZIewHVpGQKbd9vo28x9W50ynl7vx4Ow72tOkr2HVxamQjsxKqEUNZgRyE0TEpvTrwyab7Vh5At7ooo2mVHT3avfAThgB4CSDAeHHifMfq7u9zF5iNvEo8wINv7VZJFuTjO9sqlxYUnuyuAYhxLqodoadBpZ9/fzFQfwh8ClPBmgSI6FFumUZDyXyDaQCswc/H19tlBaJv2D6spqsX/jOIDcwSP533ksQaYymcS1QJWdSFzcw5GkeRgnmOUdfXD3JfyzzY/7MNlwQAjWm/BTTIupE3ShRVxiHIVrJ4DO+lUiH523s+YM+2ia+wpeC5hGc5knwcyxc1Jb/QLGopfbsp81vR2RmkpB+RuJhRb9oWWT78Uyctv+Ir40t9LpuWKHHN8z1Oft4Pq9GC2bB1AqntPNIWmTmf11p76mxb0i7dUBiMgsfkkfEQYL7skPk05yc0kUsSLOUt6OKZqcd3/x4vSSeDigeEytO7IdO6JYwC8o7uXiR2a8d/unjAYUOZH2YIvKJAkRUb2DMXcK7Gpnbg/kj2S0pwV50b8w3t4QUildoDygK3eaPZnDDkfFBJujdgmF1fTAEwdLHjSKkmWzvBBYTouQYHqLGDIhuXE6QuD33Qr/f4S6zl+Y2px1XY60NcCCxWKeNO8Pl9Rqh9FKw=
