language: python
dist: xenial
python: '3.7'
sudo: false
jobs:
  include:
  - stage: test
    install: pip3 install twilio flask fuzzywuzzy requests firebase_admin
    script: echo "Temporary holding place until the test suite exists"
  - stage: deploy
    env:
      global:
        - secure: xGf4K55qlkA2JxMzDidjbAjq9JeXjHxdHypvkX84evvrnoSVgJMmBixz8sElJQKkIrWgpUiJC2TE5Q7BQehcrVli3JYLh7UX76Iq3ELio2BzzDR4nB/lwDJMp5ELWBZhSGLFr8jIO0+2FaPRAhZKWtKgG6rCuQakyXbMXTdnioo9G+dWh/rXit5dfUopCx7IgBlJelY4JTomMGCJ0onSEcq+O6LnlRDHMjtGcqA7q4/bPqCDbIhonEVL2QdbppjCeU0kGN43kf3ae3uZers9yEx51+SsEfiatv84j6X1x3CDue66Uq40U/iZOlhDoVHX5AhQIFwOTtp6b3fFpI1GCiKea4g4B5Kx4ityJgXIsDO8LlxYfIIiyjlk9u5/ARJAJoTpayKECNgJz6JdnfZMDEHTj9Ov4ixa1+4H9oMpqTiiLGLPq82oRomE7w8VxPOzdCUhj0hbzXgmO6QffctWWKNXaoyZNQavL4Y++Z4A6QISwbKZj3bsX5bQdjdM8mMh+IKC0Zp3KnV8JN46QB4oquGO4UjcYpa4VsJYwSE3C+AhKHvFR0UkEDS80oNe/JIP/Br0MNtOb4sbOk0pXwTBdqclvOudd1OCyqyvgiqoxQ7SbAzGnD9OG1n9vzVmHeHIfNEKmnpiOOI7PmAmq/qFiYNdo3CPbPx6lWhtArRr3PA=
        - secure: ktCuLfE+ZMveQgMMj1ykqsGMtw5fkWXGOfCS4h9jiFzABS7pI/2b56DtXxT9QOGlXAm1mz6StXMmfJjZDGp4E7thU+TnIgAi/qNdd4iOnTbVOfpdHT0GruBL7iG1zTTGHWvE+sQfObsfkHOziS2AGx3bTY82/nqY6NY/SUcS/n2LrdAcEV4lGaVmUZ3y/miFzGgZcbkj6Ta1I4rB+tHQm3TMTJdUjW5pfHuR8Qq40KEl/yfv4q0EY0IXqKnurxw6jIFLNC7ofhERLM1r2VUe7vm7L7dDgRAzepIbF3KxZN66ZiFWQVLXA725dZxQHdfmKvKnYtxxvaDe+wdOguHBFz3XzTkLVnA9UunHQf7jEI50TNtmGGeJo4mQVtP2Z82Ka+VPC2F3o08IRZdi8qLb1cBc+yf+pg+sNjcDoJvcTsjj4A57bpCMxPIwKrf5g7l9SBdRaqy7GSfMlooVqWg4ofwy546NTsLozaYkfmM8wlZf29LeEJghL+fX2eBmsjv66c7him39xuowFw+OkhfEz6FryPIqihOJR2PbS+WradRtq5+OUbKhLTSL5nYUmIJckeq9+ZxwhmpH4QqokpWCMFRcoxDmT6+LGzZpgKh9oFiKBmIp/3elOf2YTx8N/bV5lr9fktJuV5xnav0I8wH66cvGomU2Y37z10zO1WJsNTE=
    install: false
    script: echo $DEPLOY_SCRIPT | bash
    after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - "./send.sh success $WEBHOOK_URL"
stages:
- test
- name: deploy
  if: type = push AND repo = orange-alliance/TOA-Text AND branch = master
